
START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA ORMModel1;

SET search_path TO ORMMODEL1,"$user",public;

CREATE TABLE ORMModel1.Player
(
	playerNr INTEGER NOT NULL,
	firstName CHARACTER VARYING NOT NULL,
	lastName CHARACTER VARYING NOT NULL,
	teamName CHARACTER VARYING NOT NULL,
	"(.Nr)" BOOLEAN,
	CONSTRAINT Player_PK PRIMARY KEY(playerNr)
);

CREATE TABLE ORMModel1.Club
(
	clubId SERIAL NOT NULL,
	name CHARACTER VARYING NOT NULL,
	travelTimeMinutes TIME,
	CONSTRAINT Club_PK PRIMARY KEY(clubId)
);

CREATE TABLE ORMModel1.TeamPlaysAgaintAClub
(
	clubId INTEGER NOT NULL,
	teamName CHARACTER VARYING NOT NULL,
	CONSTRAINT TeamPlaysAgaintAClub_PK PRIMARY KEY(teamName, clubId)
);

ALTER TABLE ORMModel1.TeamPlaysAgaintAClub ADD CONSTRAINT TeamPlaysAgaintAClub_FK FOREIGN KEY (clubId) REFERENCES ORMModel1.Club (clubId) ON DELETE RESTRICT ON UPDATE RESTRICT;

COMMIT WORK;
